0xla/cpsc455-project

client/src/App/App.css, client/src/components/TabMenu.tsx, client/src/pages/Homepage.tsx
=> tab toggle component

client/package-lock.json, client/package.json, client/src/App/App.tsx, client/src/Validation/EmailValidation.tsx, client/src/Validation/PasswordResetValidation.tsx, client/src/pages/ForgotPassword.tsx, client/src/pages/PasswordReset.tsx, client/src/pages/SignIn.tsx, client/src/pages/Signup.tsx, package-lock.json, server/controllers/authControllers.ts, server/models/user.model.ts, server/package-lock.json, server/package.json, server/router.ts, server/utils/sendEmail.ts
Implemented password reset backend and frontend.
Email API used: [SendGrid](https://sendgrid.com/)
When users click forget password they are prompted to enter their email. The email is sent to the endpoint via the request body. If the email exists in the database, an email is sent using SendGrid API. Simultaneously, a password reset token and password timeout token are set in database. If there are any errors, the password reset token and timeout token are cleared from the database.
The user can then go to the URL provided in the email. The URL param contains the hashed reset token. The user is prompted to enter their new password. When they click reset, the reset token is received in the backend, then the database is queried for a user that has that matching reset token. It's also …
=> Password Reset

client/package-lock.json, client/package.json, client/src/components/ImageUpload.tsx, client/src/util/functions.ts, server/.gitignore, server/controllers/authControllers.ts, server/controllers/imageController.ts, server/middleware/upload.ts, server/models/user.model.ts, server/package-lock.json, server/package.json, server/router.ts, server/server.ts
- uploads image to google cloud storage and stores the google cloud image url in the user document's images field
- decoded the ```authToken``` from local storage to retrieve the logged in user's id
Frontend:
Google cloud storage:
MongoDB:
=> image upload

server/controllers/userControllers.ts, server/errors/userErrors.ts, server/router.ts
Created user search endpoint. 
http://localhost:5000/api/users  will return a list of all users (I chose to include all the details of the user from the database because I think it will be useful in the future). Query parameters can be specified to allow searching for any number of usernames.
Tested with postman. Examples below:
**no filtering (all users returned)**
**filtering by multiple usernames:**
username does not exist:
=> Finish user search endpoint

server/controllers/userControllers.ts, server/errors/userErrors.ts, server/router.ts
Endpoint that returns user info based off of id sent in URL parameter. For example:
**user with matching id exists:**
**user with matching id does not exist:**
=> Finish individual user search endpoint

server/controllers/userControllers.ts
=> Remove sensitive fields from user search response

client/src/components/TopNavigation.tsx, client/src/pages/SignIn.tsx, client/src/pages/Signup.tsx, client/src/statics/text.ts
Created directory to store constants that will be used throughout the app. Changed the dummy text for login/signup to Anagram.
=> Create static constants for name of App

client/src/components/ImageCard.tsx, client/src/components/ImageUpload.tsx, client/src/dummydata/imagesPlaceholder.ts, client/src/pages/Homepage.tsx, client/src/slices/userSlice.tsx, client/src/util/functions.ts, server/controllers/imageController.ts, server/models/user.model.ts, server/package-lock.json, server/package.json, server/router.ts
- also added a few actions: (1) setImages, (2) setUsername, (3) addImage to update the reducer as necessary
=> Retrieve user data from backend and hook to FE

client/src/components/ImageUpload.tsx, client/src/components/TopNavigation.tsx, client/src/pages/Homepage.tsx, client/src/pages/SignIn.tsx, client/src/slices/userSlice.tsx, client/src/util/functions.ts
This PR addresses #51 and #7
- When the user signs-in, their ```authToken``` will be stored as a redux state and **also** in the local storage
- If the user tries to access the ```/homepage``` route but has not signed in, they will be redirected to the sign-up page
- if the user refreshes the page from homepage, the redux state will be reset so we first check if there's an ```authToken``` in the local storage. If it's there, we will set the ```authToken``` state to the one stored in the local storage and the user will **not** be redirected to the sign-up page
- when the user signs out, the ```authToken``` in local storage will be wiped and they will be redirected to the sign-up page
=> authtoken stored as redux state when user signs in

server/controllers/userControllers.ts, server/models/user.model.ts, server/router.ts
added the endpoints for follow and unfollow
haven't been able to test as of yet.
Update : Tested & Working
Real time updates happening in the MongoDB database.
Also added the getUser Endpoint
=> endpoints for follow and unfollow

server/controllers/userControllers.ts
changed followers & followings list structure to include objects of id & username to store in the Database.
follow : 
unfollow:
=> List Structure Change

client/src/components/ImageUpload.tsx, server/controllers/imageController.ts
- small bug fix
- currently, if you upload an image, the frontend will turn blank. This is becuase I was returning an incorrect image type in ```imageController``` to the frontend and using it to update the redux state. Since the```ImageCard``` component could not read this format, the frontend would crash.
=> image upload bug fix

client/src/components/ImageUpload.tsx, client/src/pages/Homepage.tsx, client/src/slices/userSlice.tsx, client/src/types.ts, server/controllers/imageController.ts, server/models/user.model.ts, server/package-lock.json, server/package.json, server/router.ts
#34 
- added an ```imageCategories``` field for the ```user``` model
- each time a user uploads an image, the ```imageCategories``` array will update (both db and the redux state)
- will be using this field for creating a piechart that represents the images of the user #10 
- Realized I didn't need another endpoint for this and could simply call the google vision API from the image upload endpoint. 
The original plan was to apply image analysis to each image of the user each time a new image was uploaded but that's less efficient than just doing the google vision analysis on each image upload
=> google vision analysis

client/src/components/TopNavigation.tsx
=> redirect to signin page on logout

client/package-lock.json, client/package.json, client/src/components/PieChart.tsx, client/src/pages/Homepage.tsx, client/tsconfig.json
=> Image analysis charts

client/src/App/App.tsx, client/src/components/ImageCard.tsx, client/src/components/ImageUpload.tsx, client/src/components/SearchBar.tsx, client/src/components/TopNavigation.tsx, client/src/pages/PageNotFound.tsx, client/src/pages/Settings.tsx, client/src/pages/SignIn.tsx, client/src/pages/Signup.tsx, client/src/pages/UserPage.tsx, client/src/slices/userSlice.tsx, client/src/util/functions.ts, server/models/user.model.ts
Users can search for and view other user profiles. 
- Homepage no longer exists (replaced with user page)
- User search now displays no results helper text.
- Clicking on Anagram button on top navigation takes user back to their profile (also added top navbar redirects).
- JWT now also stores username along with user id of logged in user.
=> Finish user profiles

client/src/pages/UserPage.tsx
- the user page didnt have piechart and imagecategories dispatch
=> add piechart and imagecategories stuff to userpage

client/src/pages/UserPage.tsx
Fixed unique key react warning.
=> Fix react key warning

client/src/pages/SignIn.tsx, client/src/pages/Signup.tsx, server/models/user.model.ts
Changed fetch calls to axios calls. Fixed bug with bad email validation. Updated error message on failed login to be more accurate.
=> Daniel/axios  consistency

client/src/components/Popup.tsx, client/src/pages/UserPage.tsx, client/src/types.ts, client/src/util/constants.ts, server/controllers/userControllers.ts, server/router.ts
Fixed follow/unfollow logic. Users can now click on any user in their following/follower list and be taken to their profile.
=> Refactor follow/unfollow frontend and backend code

client/package-lock.json, client/package.json, client/src/components/ImageUpload.tsx, client/src/util/functions.ts, server/controllers/imageController.ts, server/middleware/upload.ts
This PR consists of the following:
- added toast messages for successful upload / unsuccessful upload
- updated the max size of uploaded image
- loading spinner will not appear if the user clicks upload and no image has been selected #85 
- if the image uploaded is too large, the upload will fail and a toast message will appear. The loading spinner will still dissappear
- same image can be uploaded twice now #72
=> Image upload and loading spinner bugs

client/src/util/functions.ts, server/controllers/imageController.ts, server/models/user.model.ts
=> Include username field for each image object uploaded

client/src/components/ImageCard.tsx
Small bug when changing name of data received from following.
=> Fix feed bug when liking post

client/src/components/ImageCard.tsx, client/src/components/ImageHeader.tsx, client/src/components/ImageUpload.tsx, client/src/components/SuggestedUserCard.tsx, client/src/pages/UserPage.tsx, client/src/slices/userSlice.tsx, client/src/types.ts, client/src/util/functions.ts, server/controllers/authControllers.ts, server/controllers/imageController.ts, server/models/user.model.ts
- Added necessary logic so profile pictures are displayed in all locations they're supposed to be
- Set duration on toast message
- Permanently display suggested users at bottom of feed
- Added refresh button and extracted some of the axios calls / duplicated code out to functions.ts
- Added helper text to main page if user hasn't uploaded any pictures
- Hard coded frontend URL
=> Update all profile pictures accordingly using local state

README.md
- Please refer to section 8 of this rubric: https://blogs.ubc.ca/cpsc4552022s/assessment-rubrics/#sec-7 
to make sure that I'm not missing anything
- this includes all the sections except for **description for above and beyond functionality**
- also every member needs to write about their own contributions (please refer to the rubric when writing this)
=> README final submission requirements

client/src/components/ImageCard.tsx, client/src/pages/UserPage.tsx, client/src/slices/userSlice.tsx, client/src/util/functions.ts
- Fixed bug where a user's photos would be set to the photos of a user they follow when they like their post on feed. 
- Cleaned up some of the try catch blocks
- Remove some uncommented code
=> Fix bug when liking/unliking post on feed

README.md
- added some examples of the data we stored into our db in the mongodb section
=> elborate on mongodb section with examples of data which we stored
